"""empty message

Revision ID: 75560300d1c7
Revises: 4b8dcf1c4b02
Create Date: 2021-04-10 18:55:33.651436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75560300d1c7'
down_revision = '4b8dcf1c4b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_likes_read_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_likes_read_time', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
